<?php

use Illuminate\Database\Seeder;

class CityTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * @return void
     */
    public function run()
    {
        $city_en = array('arar',
            'sukaka',
            'al-qurayat',
            'rafhaa',
            'Dawmat aljandal',
            'dharmaa',
            'Al-mozahmyah',
            'Al-quayeiah',
            'tabarjal',
            'Hafr albaten',
            'tabouk',
            'Al-ola',
            'Almdina',
            'Makka',
            'jeddah',
            'Al-taief',
            'yanbu',
            'Khamis mushait',
            'abhaa',
            'suaier',
            'jaizan',
            'najran',
            'sharoura',
            'Al-darb',
            'Al-baha',
            'Al-nemas',
            'Al-qouz',
            'Al-qunfuthah',
            'bisha',
            'bish',
            'Sarat abida',
            'Ahd rufaida',
            'Ahd almasareha',
            'Wadi ben hashbal',
            'Abu arish',
            'sabiaa',
            'almadhaya',
            'samta',
            'baljarshi',
            'bareq',
            'farasan',
            'alhariq',
            'haael',
            'turaif',
            'tarib',
            'Dharan aljnoub',
            '    Al-riyadh',
            'Al-kharj',
            'Hawtat bni tamim',
            'Al-aflaj',
            'Al-sulaiel',
            'Wadi aldawaser',
            'ranyah',
            'tathlith',
            'malham',
            'aljubailah',
            'remah',
            'Hawtat sudair',
            'alqasim',
            'buraidah',
            'enayzah',
            'almothanab',
            'albukairayah',
            'Al-asyah',
            'Al-zulfi',
            'afif',
            'algat',
            'almajmaah',
            'Al-ras',
            'Al-badaea',
            'shaqraa',
            'Al-dawadmi',
            'Al-dammam',
            'Al-ahsaa',
            'Al-jubail',
            'Al-khubar',
            'Al-qatif',
            'baqiq',
            'Al-nuaiariah',
            'Al-khafji',
            'Al-dhahran',
            'haradh',
            'oraiarah',
            'Abu-ajram',
            'Al-dareya',
            'haurymelaa',
            'jalajel',
            'Al-jawf',
            'Al-jafr',
            'Al-laith',
            'amluj',
            'Al-ayoun',
            'Al-wadyain',
            'Al-arean',
            'Al-quarin',
            'Riyadh alkhubaraa',
            'Al-shamasiah',
            'Al-quarah',
            'turba',
            'baqaa',
            'badar',
            'alwajh',
            'balqarn',
            'Al-nabhaniah',
            'Al-makhwah',
            'Al-majareda',
            'dhamad',
            'Ras tanoura',
            'rabegh',
            'Rafaie aljamsh',
            'thahban',
            'Alj-amoum',
            'Al-bada',
            'Al-abwaa',
            'thadeq',
            'haqal',
            'khaibar',
            'tarout',
            'taimaa',
            'Al-oyayna',
            'sultana',
            'Al-okair',
            'Oyoun aljawaa',
            'Al-qaysouma',
            'Al-harajah',
            'tandaha',
            'Khaibr aljnoub',
            'samakh',
            'Rejal alma',
            'Aqbat alsamma',
            'Mahaiel asir',
            'asir',
            'alsoudah',
            'Bani malek',
            'Al-qura',
            'Al-amaryah',
            'Al-ayadabi',
            'Al-ghazala',
            'Al-aredha',
            'Al-shannan',
            'Al-sharqiah',
            'Al-raith',
            'Al-kharma',
            'Al-kharkhir',
            'Al-hanaqia',
            'Al-harth',
            'Al-jamoum',
            'Al-bada',
            'Al-abwaa',
            'Al-ertwaeyah',
            'dhebaa',
            'mastoura',
            'Al-omaran',
            'Sabt alaya',
            'tanouma',

        );
        $city_ar = array(
            'عرعر',
            'سكاكا',
            'القريات',
            'رفحاء',
            'دومة الجندل',
            'ضرماء',
            'المزاحمية',
            'القويعية',
            'طبرجل',
            'حفر الباطن',
            'تبوك',
            'العلا',
            'المدينة المنورة',
            'مكة المكرمة',
            'جدة',
            'الطائف',
            'ينبع',
            'خميس مشيط',
            'ابها',
            'صوير',
            'جيزان',
            'نجران',
            'شرورة',
            'الدرب',
            'الباحة',
            'النماص',
            'القوز',
            'القنفذة',
            'بيشة',
            'بيش',
            'سراة عبيدة',
            'احد رفيدة',
            'احد المسارحة',
            'وادي بن هشبل',
            'أبو عريش',
            'صبياء',
            'المضايا',
            'سامطة',
            'بلجرشي',
            'بارق',
            'فرسان',
            'الحريق',
            'حائل',
            'طريف',
            'طريب',
            'ظهران الجنوب',
            'الرياض',
            'الخرج',
            'حوطة بني تميم',
            'الافلاج',
            'السليل',
            'وادي الدواسر',
            'رنية',
            'تثليث',
            'ملهم',
            'الجبيلة',
            'رماح',
            'حوطة سدير',
            'القصيم',
            'بريدة',
            'عنيزة',
            'المذنب',
            'البكيرية',
            'الاسياح',
            'الزلفي',
            'عفيف',
            'الغاط',
            'المجمعة',
            'الرس',
            'البدائع',
            'شقراء',
            'الدوادمي',
            'الدمام',
            'الاحساء',
            'الجبيل',
            'الخبر',
            'القطيف',
            'بقيق',
            'النعيرية',
            'الخفجي',
            'الظهران',
            'حرض',
            'عريعرة',
            'أبو عجرم',
            'الدرعية',
            'حريملاء',
            'جلاجل',
            'الجوف',
            'الجفر',
            'الليث',
            'املج',
            'العيون',
            'الواديين',
            'العرين',
            'القرين',
            'رياض الخبراء',
            'الشماسية',
            'القوارة',
            'تربة',
            'بقعاء',
            'بدر',
            'الوجه',
            'بالقرن',
            'النبهانية',
            'المخواة',
            'المجاردة',
            'ضمد',
            'راس تنورة',
            'رابغ',
            'رفايع الجمش',
            'ذهبان',
            'الجموم',
            'البدع',
            'الابواء',
            'ثادق',
            'حقل',
            'خيبر',
            'تاروت',
            'تيماء',
            'العيينة',
            'سلطانة',
            'العقير',
            'عيون الجواء',
            'القيصومة',
            'الحرجة',
            'تندحة',
            'خيبر الجنوب',
            'صمخ',
            'رجال المع',
            'عقبة الصماء',
            'محايل عسير',
            'عسير',
            'السودة',
            'بني مالك',
            'القرى',
            'العمارية',
            'العيدابي',
            'الغزالة',
            'العارضة',
            'الشنان',
            'الشرقية',
            'الريث',
            'الخرمة',
            'الخرخير',
            'الحناكية',
            'الحرث',
            'الجموم',
            'البدع',
            'الابواء',
            'الارتوائية',
            'ضباء',
            'مستورة',
            'العمران',
            'سبت العلايا',
            'تنومة',);
        $city_ur = array();

        $city = array();
        for ($i = 0; $i < count($city_en); $i++)
        {
            $city[$i]['country_id'] = 1;
            $city[$i]['en'] = $city_en[$i];
            $city[$i]['ar'] = $city_ar[$i];
//            $city[$i]['ur'] = $city_ur[$i];
        }

        \App\Model\City::insert($city);
    }
}
